stages:
  - build

docker-build:
  image: docker:cli
  stage: build
  services:
    - name: docker:dind
      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
      command: [ "dockerd-entrypoint.sh", "--insecure-registry=registry.service.cc:443" ]
  variables:
    # issue https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4566#note_199261985
    DOCKER_REGISTRY: registry.service.cc:443
    DOCKER_HOST: tcp://docker:2375
    TENCENT_REGISTRY: ccr.ccs.tencentyun.com
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - echo "Build Start!!"
    - if [ -n "$CI_COMMIT_TAG" ]; then export VERSION="$CI_COMMIT_TAG"; else export VERSION="v1.1.4-${CI_COMMIT_SHORT_SHA}"; fi
    - export DOCKER_IMAGE_NAME="$DOCKER_REGISTRY/nginx-proxy:$VERSION"
    - export DOCKER_IMAGE_LATEST="$DOCKER_REGISTRY/nginx-proxy:latest"
    - export DOCKER_IMAGE_TENCENT="$TENCENT_REGISTRY/cocofhu/nginx-proxy:$VERSION"
    - export DOCKER_IMAGE_TENCENT_LATEST="$TENCENT_REGISTRY/cocofhu/nginx-proxy:latest"
    - echo $DOCKER_IMAGE_NAME
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "$CI_DEFAULT_BRANCH" ]] || [[ -n "$CI_COMMIT_TAG" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_LATEST"
        docker push "$DOCKER_IMAGE_LATEST"
        docker login ccr.ccs.tencentyun.com --username="$TENCENT_DOCKER_USER" --password="$TENCENT_DOCKER_PASS"
        docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_TENCENT"
        docker push "$DOCKER_IMAGE_TENCENT"
        docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_TENCENT_LATEST"
        docker push "$DOCKER_IMAGE_TENCENT_LATEST"
      fi
    - echo "Build success!!"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile