# 生产环境 Docker Compose 配置
version: '3.8'

services:
  nginx-proxy:
    image: ${DOCKER_REGISTRY:-ccr.ccs.tencentyun.com}/cocofhu/nginx-proxy:${VERSION:-latest}
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - nginx_data:/app/data
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/nginx/certs
      - nginx_logs:/var/log/nginx
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/rules"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  nginx:
    image: nginx:alpine
    container_name: nginx-main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      nginx-proxy:
        condition: service_healthy
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可选：日志收集
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: nginx-filebeat
    user: root
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
    depends_on:
      - nginx
      - nginx-proxy
    restart: unless-stopped
    profiles:
      - logging

volumes:
  nginx_data:
    driver: local
  nginx_conf:
    driver: local
  nginx_certs:
    driver: local
  nginx_logs:
    driver: local

networks:
  default:
    name: nginx-proxy-network